easy_admin:
  entities:
    Skill:
      class: 'App\Entity\Skill'
      templates:
        list: 'admin/skill/list.html.twig'
      disabled_actions: ['search']
      list:
        fields:
          - { property: 'name' }
          - { property: 'description' }
      form:
        fields:
          - { property: 'name' }
          - { property: 'description' }
          - { property: 'image', type: 'App\Form\Type\ImageType' }
