easy_admin:
  entities:
    TimelineItem:
      class: 'App\Entity\TimelineItem'
      templates:
        list: 'admin/timeline_item/list.html.twig'
      list:
        fields:
          - { property: 'position' }
          - { property: 'title' }
          - { property: 'subtitle' }
        sort: ['position', 'ASC']
      form:
        fields:
          - { property: 'title' }
          - { property: 'subtitle' }
          - { property: 'description', type: 'fos_ckeditor' }
          - { property: 'image', type: 'App\Form\Type\ImageType' }
