easy_admin:
  entities:
    TimelineItem:
      class: 'App\Entity\TimelineItem'
      controller: 'App\Controller\Admin\TimelineItemController'
      list:
        fields:
          - { property: 'position' }
          - { property: 'title' }
          - { property: 'subtitle' }
        sort: ['position', 'ASC']
      form:
        fields:
          - { property: 'position' }
          - { property: 'title' }
          - { property: 'subtitle' }
          - { property: 'description', type: 'fos_ckeditor' }
