imports:
    - { resource: ../admin/ }
easy_admin:
    translation_domain: 'admin'
    list:
        actions:
            - { name: 'edit', icon: 'flaticon2-contract' }
            - { name: 'delete', icon: 'flaticon2-trash', css_class: '' }
    new:
        actions:
            - { name: 'list', css_class: 'btn btn-default btn-bold', icon: 'flaticon2-left-arrow-1' }
    edit:
        actions:
            - { name: 'list', css_class: 'btn btn-default btn-bold', icon: 'flaticon2-left-arrow-1' }
            - { name: 'delete', css_class: 'btn btn-danger btn-bold', icon: 'flaticon2-trash' }
    design:
        menu:
            - { route: 'admin_dashboard', label: 'menu.dashboard', icon: 'th-large', default: true }
            - { route: 'home', label: 'menu.back_to_site', icon: 'home' }
            - { label: 'menu.admin' }
            - { entity: 'TimelineItem', label: 'menu.timeline_item', icon: 'history' }
            - { label: 'menu.gallery' }
            - { route: 'admin_image_index', label: 'menu.image', icon: 'images' }
        assets:
            favicon: '/favicon.png'
        form_theme: ['@EasyAdmin/form/bootstrap_4.html.twig', '@FOSCKEditor/Form/ckeditor_widget.html.twig', 'admin/form_theme.html.twig']
        templates:
            layout: 'admin/layout.html.twig'
            new: 'admin/new.html.twig'
            edit: 'admin/edit.html.twig'
            menu: 'admin/menu.html.twig'
            list: 'admin/list.html.twig'
            paginator: 'admin/paginator.html.twig'
