easy_admin:
    entities:
        TimelineItem:
            class: 'App\Entity\TimelineItem'
            controller: 'App\Controller\Admin\TimelineItemController'
            list:
                fields:
                    - { property: 'position' }
                    - { property: 'title' }
                    - { property: 'subtitle' }
                    - { property: 'image', template: 'admin/timeline_item/field_image.html.twig' }
                sort: ['position', 'ASC']
            form:
                fields:
                    - { property: 'position' }
                    - { property: 'title' }
                    - { property: 'subtitle' }
                    - { property: 'imageFile', type: 'file' }
                    - { property: 'description', type: 'fos_ckeditor' }
    translation_domain: 'admin'
    list:
        actions:
            - { name: 'edit', icon: 'flaticon2-contract' }
            - { name: 'delete', icon: 'flaticon2-trash', css_class: '' }
    new:
        actions:
            - { name: 'list', css_class: 'btn btn-default btn-bold', icon: 'flaticon2-left-arrow-1' }
    edit:
        actions:
            - { name: 'list', css_class: 'btn btn-default btn-bold', icon: 'flaticon2-left-arrow-1' }
            - { name: 'delete', css_class: 'btn btn-danger btn-bold', icon: 'flaticon2-trash' }
    design:
        menu:
            - { route: 'home', label: 'menu.back_to_site', icon: 'home' }
            - { label: 'menu.admin' }
            - { entity: 'TimelineItem', label: 'menu.timeline_item', icon: 'history' }
        assets:
            favicon: '/favicon.png'
        form_theme: ['@EasyAdmin/form/bootstrap_4.html.twig', '@FOSCKEditor/Form/ckeditor_widget.html.twig', 'admin/form_theme.html.twig']
        templates:
            layout: 'admin/layout.html.twig'
            new: 'admin/new.html.twig'
            edit: 'admin/edit.html.twig'
            menu: 'admin/menu.html.twig'
            list: 'admin/list.html.twig'
            paginator: 'admin/paginator.html.twig'
