nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Dev-Alizon
            version: ''
        definitions:
            image:
                type: object
                properties:
                    id:
                        type: integer
                        example: 1
                    name:
                        type: string
                        example: image.jpg
                    size:
                        type: string
                        example: 100k
                    url:
                        type: string
                        example: /resize/xs/uploads/image.jpg
                    year:
                        type: integer
                        example: 2020
            folder:
                type: object
                properties:
                    year:
                        type: integer
                        example: 2020
                    count:
                        type: integer
                        example: 11
