imports:
    - { resource: ../api/ }
nelmio_api_doc:
    documentation:
        info:
            title: Dev-Alizon
            version: ''
    areas:
        path_patterns:
            - ^/api(?!/doc$)
