vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y'
                    date_time_property: createdAt
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
