vich_uploader:
    db_driver: orm

    mappings:
        timeline_items:
            uri_prefix: /uploads/images/timeline_items
            upload_destination: '%kernel.project_dir%/public%app.path.timeline_items_images%'
